
// https://en.wikipedia.org/wiki/Single_Compilation_Unit
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <time.h>
#include "../lib/argparse.c"
#include "../lib/arena.c"
#include "../lib/arraylist.c"
#include "util.c"
#include "Syntax/syntaxTree.c"
#include "diagnostics.h"
#include "Syntax/lexer.c"
#include "Syntax/parser.c"
#include "Binding/ast.c"
#include "Binding/binder.c"
#include "emit/Cemitter.c"
#include "diagnostics.c"